# Generated by Django 5.2.1 on 2025-05-24 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_favoris'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='localisation',
            field=models.CharField(default='Casablanca', max_length=255),
        ),
        migrations.AddField(
            model_name='categorie',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='App.categorie'),
        ),
        migrations.AlterField(
            model_name='administrateur',
            name='image',
            field=models.ImageField(max_length=255, upload_to='admin/'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='statut',
            field=models.BooleanField(default=False),
        ),
    ]
