# Generated by Django 5.2.1 on 2025-05-27 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_administrateur_is_superuser_annonce_localisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='annonce',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ann', to='App.annonce'),
        ),
        migrations.AlterField(
            model_name='administrateur',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
